name: docker-build-push
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: build Python HelloWorld app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: python-helloworld:latest
          platforms: linux/amd64,linux/arm64
    
